packages: []

allowBuilds:
  "@parcel/watcher": false
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  vue-demi: true

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - lyric-dom
  - lyric-kit
  - "@applemusic-like-lyrics/core"

overrides:
  node-abi: ^4.33.0
